/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as LeaderboardChallengeIdIndexRouteImport } from './routes/leaderboard/$challengeId/index'
import { Route as ChallengesChallengeIdIndexRouteImport } from './routes/challenges/$challengeId/index'
import { Route as AppSubmissionsIndexRouteImport } from './routes/app/submissions/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppReplaysIndexRouteImport } from './routes/app/replays/index'
import { Route as AppProfileIndexRouteImport } from './routes/app/profile/index'
import { Route as AppSubmissionsNewRouteImport } from './routes/app/submissions.new'
import { Route as AppSubmissionsSubmissionIdRouteImport } from './routes/app/submissions.$submissionId'
import { Route as AppRunsRunIdRouteImport } from './routes/app/runs.$runId'
import { Route as AppOrganizerTrafficProfilesIndexRouteImport } from './routes/app/organizer/traffic-profiles/index'
import { Route as AppOrganizerScoringIndexRouteImport } from './routes/app/organizer/scoring/index'
import { Route as AppOrganizerChallengesIndexRouteImport } from './routes/app/organizer/challenges/index'
import { Route as AppAdminReviewIndexRouteImport } from './routes/app/admin/review/index'
import { Route as AppAdminModerationIndexRouteImport } from './routes/app/admin/moderation/index'
import { Route as AppAdminAuditIndexRouteImport } from './routes/app/admin/audit/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LeaderboardChallengeIdIndexRoute =
  LeaderboardChallengeIdIndexRouteImport.update({
    id: '/leaderboard/$challengeId/',
    path: '/leaderboard/$challengeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChallengesChallengeIdIndexRoute =
  ChallengesChallengeIdIndexRouteImport.update({
    id: '/challenges/$challengeId/',
    path: '/challenges/$challengeId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSubmissionsIndexRoute = AppSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReplaysIndexRoute = AppReplaysIndexRouteImport.update({
  id: '/replays/',
  path: '/replays/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsNewRoute = AppSubmissionsNewRouteImport.update({
  id: '/submissions/new',
  path: '/submissions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsSubmissionIdRoute =
  AppSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => AppRoute,
  } as any)
const AppRunsRunIdRoute = AppRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerTrafficProfilesIndexRoute =
  AppOrganizerTrafficProfilesIndexRouteImport.update({
    id: '/organizer/traffic-profiles/',
    path: '/organizer/traffic-profiles/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizerScoringIndexRoute =
  AppOrganizerScoringIndexRouteImport.update({
    id: '/organizer/scoring/',
    path: '/organizer/scoring/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizerChallengesIndexRoute =
  AppOrganizerChallengesIndexRouteImport.update({
    id: '/organizer/challenges/',
    path: '/organizer/challenges/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminReviewIndexRoute = AppAdminReviewIndexRouteImport.update({
  id: '/admin/review/',
  path: '/admin/review/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModerationIndexRoute = AppAdminModerationIndexRouteImport.update({
  id: '/admin/moderation/',
  path: '/admin/moderation/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditIndexRoute = AppAdminAuditIndexRouteImport.update({
  id: '/admin/audit/',
  path: '/admin/audit/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/app/': typeof AppIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/replays/': typeof AppReplaysIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/challenges/$challengeId/': typeof ChallengesChallengeIdIndexRoute
  '/leaderboard/$challengeId/': typeof LeaderboardChallengeIdIndexRoute
  '/app/admin/audit/': typeof AppAdminAuditIndexRoute
  '/app/admin/moderation/': typeof AppAdminModerationIndexRoute
  '/app/admin/review/': typeof AppAdminReviewIndexRoute
  '/app/organizer/challenges/': typeof AppOrganizerChallengesIndexRoute
  '/app/organizer/scoring/': typeof AppOrganizerScoringIndexRoute
  '/app/organizer/traffic-profiles/': typeof AppOrganizerTrafficProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/app': typeof AppIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/app/profile': typeof AppProfileIndexRoute
  '/app/replays': typeof AppReplaysIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/submissions': typeof AppSubmissionsIndexRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdIndexRoute
  '/leaderboard/$challengeId': typeof LeaderboardChallengeIdIndexRoute
  '/app/admin/audit': typeof AppAdminAuditIndexRoute
  '/app/admin/moderation': typeof AppAdminModerationIndexRoute
  '/app/admin/review': typeof AppAdminReviewIndexRoute
  '/app/organizer/challenges': typeof AppOrganizerChallengesIndexRoute
  '/app/organizer/scoring': typeof AppOrganizerScoringIndexRoute
  '/app/organizer/traffic-profiles': typeof AppOrganizerTrafficProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/app/': typeof AppIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/app/runs/$runId': typeof AppRunsRunIdRoute
  '/app/submissions/$submissionId': typeof AppSubmissionsSubmissionIdRoute
  '/app/submissions/new': typeof AppSubmissionsNewRoute
  '/app/profile/': typeof AppProfileIndexRoute
  '/app/replays/': typeof AppReplaysIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/submissions/': typeof AppSubmissionsIndexRoute
  '/challenges/$challengeId/': typeof ChallengesChallengeIdIndexRoute
  '/leaderboard/$challengeId/': typeof LeaderboardChallengeIdIndexRoute
  '/app/admin/audit/': typeof AppAdminAuditIndexRoute
  '/app/admin/moderation/': typeof AppAdminModerationIndexRoute
  '/app/admin/review/': typeof AppAdminReviewIndexRoute
  '/app/organizer/challenges/': typeof AppOrganizerChallengesIndexRoute
  '/app/organizer/scoring/': typeof AppOrganizerScoringIndexRoute
  '/app/organizer/traffic-profiles/': typeof AppOrganizerTrafficProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/signin'
    | '/app/'
    | '/challenges/'
    | '/leaderboard/'
    | '/app/runs/$runId'
    | '/app/submissions/$submissionId'
    | '/app/submissions/new'
    | '/app/profile/'
    | '/app/replays/'
    | '/app/settings/'
    | '/app/submissions/'
    | '/challenges/$challengeId/'
    | '/leaderboard/$challengeId/'
    | '/app/admin/audit/'
    | '/app/admin/moderation/'
    | '/app/admin/review/'
    | '/app/organizer/challenges/'
    | '/app/organizer/scoring/'
    | '/app/organizer/traffic-profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/app'
    | '/challenges'
    | '/leaderboard'
    | '/app/runs/$runId'
    | '/app/submissions/$submissionId'
    | '/app/submissions/new'
    | '/app/profile'
    | '/app/replays'
    | '/app/settings'
    | '/app/submissions'
    | '/challenges/$challengeId'
    | '/leaderboard/$challengeId'
    | '/app/admin/audit'
    | '/app/admin/moderation'
    | '/app/admin/review'
    | '/app/organizer/challenges'
    | '/app/organizer/scoring'
    | '/app/organizer/traffic-profiles'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/signin'
    | '/app/'
    | '/challenges/'
    | '/leaderboard/'
    | '/app/runs/$runId'
    | '/app/submissions/$submissionId'
    | '/app/submissions/new'
    | '/app/profile/'
    | '/app/replays/'
    | '/app/settings/'
    | '/app/submissions/'
    | '/challenges/$challengeId/'
    | '/leaderboard/$challengeId/'
    | '/app/admin/audit/'
    | '/app/admin/moderation/'
    | '/app/admin/review/'
    | '/app/organizer/challenges/'
    | '/app/organizer/scoring/'
    | '/app/organizer/traffic-profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  ChallengesChallengeIdIndexRoute: typeof ChallengesChallengeIdIndexRoute
  LeaderboardChallengeIdIndexRoute: typeof LeaderboardChallengeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard/'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/leaderboard/$challengeId/': {
      id: '/leaderboard/$challengeId/'
      path: '/leaderboard/$challengeId'
      fullPath: '/leaderboard/$challengeId/'
      preLoaderRoute: typeof LeaderboardChallengeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$challengeId/': {
      id: '/challenges/$challengeId/'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId/'
      preLoaderRoute: typeof ChallengesChallengeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/submissions/': {
      id: '/app/submissions/'
      path: '/submissions'
      fullPath: '/app/submissions/'
      preLoaderRoute: typeof AppSubmissionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/replays/': {
      id: '/app/replays/'
      path: '/replays'
      fullPath: '/app/replays/'
      preLoaderRoute: typeof AppReplaysIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions/new': {
      id: '/app/submissions/new'
      path: '/submissions/new'
      fullPath: '/app/submissions/new'
      preLoaderRoute: typeof AppSubmissionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions/$submissionId': {
      id: '/app/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/app/submissions/$submissionId'
      preLoaderRoute: typeof AppSubmissionsSubmissionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs/$runId': {
      id: '/app/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/app/runs/$runId'
      preLoaderRoute: typeof AppRunsRunIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizer/traffic-profiles/': {
      id: '/app/organizer/traffic-profiles/'
      path: '/organizer/traffic-profiles'
      fullPath: '/app/organizer/traffic-profiles/'
      preLoaderRoute: typeof AppOrganizerTrafficProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizer/scoring/': {
      id: '/app/organizer/scoring/'
      path: '/organizer/scoring'
      fullPath: '/app/organizer/scoring/'
      preLoaderRoute: typeof AppOrganizerScoringIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizer/challenges/': {
      id: '/app/organizer/challenges/'
      path: '/organizer/challenges'
      fullPath: '/app/organizer/challenges/'
      preLoaderRoute: typeof AppOrganizerChallengesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/review/': {
      id: '/app/admin/review/'
      path: '/admin/review'
      fullPath: '/app/admin/review/'
      preLoaderRoute: typeof AppAdminReviewIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/moderation/': {
      id: '/app/admin/moderation/'
      path: '/admin/moderation'
      fullPath: '/app/admin/moderation/'
      preLoaderRoute: typeof AppAdminModerationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit/': {
      id: '/app/admin/audit/'
      path: '/admin/audit'
      fullPath: '/app/admin/audit/'
      preLoaderRoute: typeof AppAdminAuditIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppRunsRunIdRoute: typeof AppRunsRunIdRoute
  AppSubmissionsSubmissionIdRoute: typeof AppSubmissionsSubmissionIdRoute
  AppSubmissionsNewRoute: typeof AppSubmissionsNewRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppReplaysIndexRoute: typeof AppReplaysIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSubmissionsIndexRoute: typeof AppSubmissionsIndexRoute
  AppAdminAuditIndexRoute: typeof AppAdminAuditIndexRoute
  AppAdminModerationIndexRoute: typeof AppAdminModerationIndexRoute
  AppAdminReviewIndexRoute: typeof AppAdminReviewIndexRoute
  AppOrganizerChallengesIndexRoute: typeof AppOrganizerChallengesIndexRoute
  AppOrganizerScoringIndexRoute: typeof AppOrganizerScoringIndexRoute
  AppOrganizerTrafficProfilesIndexRoute: typeof AppOrganizerTrafficProfilesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppRunsRunIdRoute: AppRunsRunIdRoute,
  AppSubmissionsSubmissionIdRoute: AppSubmissionsSubmissionIdRoute,
  AppSubmissionsNewRoute: AppSubmissionsNewRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppReplaysIndexRoute: AppReplaysIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSubmissionsIndexRoute: AppSubmissionsIndexRoute,
  AppAdminAuditIndexRoute: AppAdminAuditIndexRoute,
  AppAdminModerationIndexRoute: AppAdminModerationIndexRoute,
  AppAdminReviewIndexRoute: AppAdminReviewIndexRoute,
  AppOrganizerChallengesIndexRoute: AppOrganizerChallengesIndexRoute,
  AppOrganizerScoringIndexRoute: AppOrganizerScoringIndexRoute,
  AppOrganizerTrafficProfilesIndexRoute: AppOrganizerTrafficProfilesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  ChallengesChallengeIdIndexRoute: ChallengesChallengeIdIndexRoute,
  LeaderboardChallengeIdIndexRoute: LeaderboardChallengeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
